apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      env: myapp
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        env: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
