apiVersion: v1
kind: Pod
metadata:
  name: webapp-red
  labels:
    app: webapp-red
spec:
  containers:
    - name: concepts-build-image-demo
      image: concepts-build-image-demo
      command: ["color"]
      args: ["red"]
